### ISSUE TITLE
Fatal error in launcher: Unable to create process using '"C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe"  "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\conan.exe" install . --install-folder "Targets\" --build missing -s build_type= -c tools.system.package_manager:mode=install': The system cannot find the file specified.

### ISSUE THREAD

**Issue by quang-pth** [Madsycode/book-empy-engine#1]
I got this error after running the EmpyWin.bat file.
Know that i use Window 11  with python version 3.12.2 and conan version 1.61.0. 
This is the first time i use conan so i don't really know what's wrong with it. Hope you can help

**Comment by Madsycode** [comment]
Hi,
The error message you provided indicates that the system is unable to find the specified Python.exe file. This issue has nothing to do with the code, but you build the system. Make sure you are targeting Python and conan properly. Maybe you haven't installed Python globally using the environment path. In that case, you might have to create a Python virtual environment! ChatGPT can help

To resolve this issue:

1. Verify that the paths provided for Python and Conan are correct and exist on your system.
2. Ensure that Python and Conan are properly installed and configured on your system.
3. Double-check the command syntax to ensure there are no typos or missing parameters.
4. Check if there are any environment variables or system configurations that might be causing the issue.
5. If necessary, reinstall Python and Conan to ensure a clean installation.

Once you've verified and corrected any issues with the file paths and installations, you should be able to execute the command successfully.

**Comment by quang-pth** [comment]
Seems like it work after i remove and re-install both python and conan. Thank you so much
There's two thing:
- First, I think you should emphasize in your book that reader should use the same version as the time you wrote the book, because the first time i install python it's not on the same version as you (which is 3.12.x), and that cause the problem.
- Second, can you write a guideline how to build your engine for new readers like me. Cause some people have no experience on the tools you use.
Anyway, this is a great book.

**Comment by Madsycode** [comment]
Glad to hear that! The first suggestion is actually in the book; I specifically said to use the same version!
