### ISSUE TITLE
Sphere Not Showing with ComputeAmbientLight In Book 6.5.2 and Advanced-Rendering Branch

### ISSUE THREAD

**Issue by Wcarey7** [Madsycode/book-empy-engine#3]
Following along with the book and came across an issue. After completing Chapter 6.5.2 Diffuse Irradiance the sphere no longer renders and its just the skybox. If I comment out the ComputeAmbientLight being added to the result in pbr.glsl the sphere will then render but with some odd lighting. I decided to clone the Advance-Rendering branch to compare and that branch has the same issue, all I did was compiled it in VSCode and ran it and only the skybox renders. If I resize the window the sphere does show up briefly during the resizing, it's as if the skybox is overdrawing the sphere and I haven't been able to figure out why and how the ambient light is causing the issue.

**Comment by Madsycode** [comment]
Are you using a VM?

**Comment by Wcarey7** [comment]
No VM, just Windows 10. The below image is what I get after cloning the advance-rendering branch, opening it up in Visual Studio Code(Version 1.89.1), clicking Run Build Task, and then Start Debugging.
![Build Screenshot](https://github.com/Madsycode/book-empy-engine/assets/13939125/4cc4dd9f-ef5b-445d-bcab-e07aaba20dcc)

**Comment by Wcarey7** [comment]
If I make the changes to lines 391 & 392 of pbr.glsl this is what I get:
![Build Screenshot2](https://github.com/Madsycode/book-empy-engine/assets/13939125/56debc4f-d577-4035-8670-6d243fba6876)

**Comment by Madsycode** [comment]
It is good to see that you have found a way around it but what did you change in the pbr.glsl?

**Comment by Wcarey7** [comment]
I commented out the ComputeAmbientLight being added to the result on line 391

**Comment by Wcarey7** [comment]
That worked! Thanks @adoug !

**Comment by assemly** [comment]
Even after I added glBindTexture(GL_TEXTURE_2D, 0), the model is still not displayed.

OS: Windos11
I found modify SetEnvMaps() is work:
``` PBR
 EMPY_INLINE void SetEnvMaps(uint32_t irrad, uint32_t prefil, uint32_t brdf)
        {
            glUseProgram(m_ShaderID);

            // irradiance map
            glActiveTexture(GL_TEXTURE1);
            glBindTexture(GL_TEXTURE_CUBE_MAP, irrad);
            glUniform1i(u_IrradMap, 1);

            // prefiltered map
            glActiveTexture(GL_TEXTURE2);
            glBindTexture(GL_TEXTURE_CUBE_MAP, prefil);
            glUniform1i(u_PrefilMap, 2);

            // BRDF Map
            glActiveTexture(GL_TEXTURE3);
            glBindTexture(GL_TEXTURE_2D, brdf);
            glUniform1i(brdf, 3);
        }
 EMPY_INLINE void Draw(Model3D& model, PbrMaterial& material, Transform3D& transform)
{
  ....
  int32_t unit = 4; // <-- starts at unit 4
...
}
```
I found GL_TEXTURE0 awalys bind CubMap or SkyMap
